### ISSUE TITLE
ported to ruby

### ISSUE THREAD

**Issue by KINGSABRI** [catalyst256/Netscaler-Cookie-Decryptor#2]
Hello there, 
I've translated the decryptor to ruby and I see you have ported the script to more than one language. If you like, I would PR ruby to this repo as well (check [here](https://github.com/TechArchSA/Netscaler-Cookie-Decryptor)) to have multiple languages at the same place 
Note: There is an enhancement in the regex in my [version](https://github.com/TechArchSA/Netscaler-Cookie-Decryptor/blob/master/nsccookiedecrypt.rb#L19) that supports the punctuation marks as I've experienced a cookie with `!` character recently.

**Comment by amx1978** [comment]
Hello,

More than happy for you to submit a pull request to add this to the repo. Awesome work 👍
